# Generated by Django 5.2.1 on 2025-05-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_on_vacation",
            field=models.BooleanField(default=False),
        ),
    ]
